// src/components/context-menu/context-menu.tsx
import {Component, Element, EventEmitter, h, Host, Listen, Method, Prop, State, Watch, Event} from '@stencil/core';
import {CssMap} from "../../utils";
import {Point} from "../../models";

@Component({
  tag: 'wf-context-menu',
  styleUrl: 'context-menu.scss',
  shadow: true
})
export class ContextMenu {

  @Element()
  el: HTMLElement;

  @Prop()
  target: HTMLElement;

  @Prop({reflect: true, attribute: 'target'})
  targetSelector: string;

  @State()
  isHidden: boolean = true;

  @State()
  position: Point = {left: 0, top: 0};

  @Watch('target')
  targetChangeHandler(newValue: HTMLElement, oldValue: HTMLElement) {
    if (!!oldValue) {
      oldValue.removeEventListener('contextmenu', this.onContextMenu);
    }

    this.setupTarget(newValue);
  }

  @Watch('targetSelector')
  targetSelectorChangeHandler(newValue: string) {
    this.target = document.querySelector(newValue);
  }

  @Listen('click', {target: 'body'})
  handleBodyClick() {
    this.isHidden = true;
  }

  @Listen('context-menu', { target: 'body' })
  handleContextMenu() {
    this.isHidden = true;
  }

  @Event({eventName: 'context-menu', bubbles: true})
  contextMenuEvent: EventEmitter;

  @Method()
  async handleContextMenuEvent(e: MouseEvent) {
    this.onContextMenu(e);
  }

  public componentDidLoad() {
    this.setupTarget(this.target);
  }

  public render() {
    const css: CssMap = {
      left: `${this.position.left}px`,
      top: `${this.position.top}px`,
      display: this.isHidden ? 'none' : 'block'
    };
    return (
      <Host class="dropdown-menu context-menu canvas-context-menu position-fixed" style={css} onClick={this.onContextMenuClick}>
        <slot />
      </Host>
    )
  }

  private setupTarget(value: HTMLElement) {
    if (!!value) {
      value.addEventListener('contextmenu', this.onContextMenu, {capture: false});
    }
  }

  private onContextMenu = (e: MouseEvent) => {
    if (e.defaultPrevented)
      return;

    e.preventDefault();
    this.contextMenuEvent.emit();
    this.position = {left: e.pageX, top: e.pageY};
    this.isHidden = false;
  };

  private onContextMenuClick = () => {
    this.isHidden = true;
  }
}

// svelte/workflow-designer/src/components/ContextMenu/ContextMenu.svelte
﻿<script>
    //export let target;
    let hidden = true;
    let position = {left: 0, top: 0};

    $: css = {
        left: `${position.left}px`,
        top: `${position.top}px`,
        display: hidden ? 'none' : 'block'
    };
    
    export function show(e){
        onContextMenu(e);
    }

    function onContextMenu(e) {
        if (e.defaultPrevented)
            return;

        e.preventDefault();
        //this.contextMenuEvent.emit();
        position = {left: e.pageX, top: e.pageY};
        hidden = false;
    }

    function onContextMenuClick() {
        hidden = true;
    }

    // $: {
    //     if (!!target) {
    //         target.addEventListener('contextmenu')
    //     }
    // }
</script>

<svelte:body on:click={hidden=true} on:contextmenu={hidden=true}/>

<div class="dropdown-menu context-menu canvas-context-menu position-fixed" style={css} on:click={onContextMenuClick}>
    Hello Context
</div>
